#!/bin/bash

set -uo pipefail

# Add fwcd repo
cat <<EOF >> /etc/pacman.conf

[fwcd]
Server = https://github.com/fwcd/arch-repo-\$arch/releases/latest/download
SigLevel = Never
EOF

# Install useful packages
packages=(
  avahi
  curl
  git
  htop
  iwd
  man-db
  neovim
  python
  rsync
  sudo
  tmux
  yay
  zsh
)
pacman -Syu --noconfirm --needed "${packages[@]}"

# Enable services
systemctl enable avahi-daemon iwd
