#!/bin/bash

set -uo pipefail

# Replace default kernel + U-Boot with Raspberry Pi foundation's kernel + bootloader
# See https://github.com/fwcd/archlinuxarm-images/issues/3
pacman -R --noconfirm linux-aarch64 uboot-raspberrypi
pacman -Syu --noconfirm --needed linux-rpi raspberrypi-bootloader raspberrypi-firmware

# Install and enable avahi (mDNS/DNS-SD stack)
# This makes the Pi easy to find on the network (just issue ssh alarm@alarm.local)
pacman -Syu --noconfirm --needed avahi
systemctl enable avahi-daemon
