#!/bin/bash

# Set up the Raspberry Pi sysroot while chrooted into it.

set -uo pipefail

# Install Raspberry Pi foundation's kernel + bootloader due to issues with the default kernel + U-Boot
# See https://github.com/fwcd/archlinuxarm-images/issues/3
pacman -R --noconfirm linux-aarch64 uboot-raspberrypi
pacman -Syu --noconfirm --needed linux-rpi raspberrypi-bootloader raspberrypi-firmware
